//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuanLyCV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChucVu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChucVu()
        {
            this.CVs = new HashSet<CV>();
        }
    
        public int MaChV { get; set; }
        public string ChucVuTuyenDung { get; set; }
        public Nullable<int> MaCT { get; set; }
        public Nullable<decimal> MucLuong { get; set; }
        public string MoTaCongViec { get; set; }
        public string YeuCau { get; set; }
        public string PhucLoi { get; set; }
    
        public virtual CongTy CongTy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CV> CVs { get; set; }
    }
}
