//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuanLyCV.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ThongtinTaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongtinTaiKhoan()
        {
            this.CVs = new HashSet<CV>();
        }
    
        public int MaTTTK { get; set; }
        public string HoTen { get; set; }
        [EmailAddress(ErrorMessage = "Hãy nhập chính xác địa chỉ email")]
        public string Email { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string TrinhDoHocVan { get; set; }
        public string GioiThieuBanThan { get; set; }
        public Nullable<int> MaLoaiTK { get; set; }
        public Nullable<int> MaCT { get; set; }
        public string MatKhau { get; set; }
        public string CauHoiAN { get; set; }
        public string AnhDD { get; set; }
        public string SDTCN { get; set; }
    
        public virtual CongTy CongTy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CV> CVs { get; set; }
        public virtual LoaiTaiKhoan LoaiTaiKhoan { get; set; }
    }
}
